[build]
# SStandard target. IFF RiscV expands we'll use riscv32imac-unknown-none-elf (M, A og C)

target = "riscv32i-unknown-none-elf"

[target.riscv32i-unknown-none-elf]
# Tell the linker to use our custom memory layout file (memory.ld), which defines where in memory the code and data should be placed.
rustflags = [
    "-C", "link-arg=-Tmemory.ld",
]

[profile.dev]
# Even if dev mode, we want to optimize for size, since we have very limited flash memory. But we also want some debug info, so we can test and debug on real hardware.
opt-level = "s"      #  OPtimize for size, but not as aggressively as "z", so we still get some debug info.
panic = "abort"      #  As no OS we cant catch thus rust unwinding turned off

[profile.release]
opt-level = "z"      # max optimization for size, even if it means no debug info. We want to fit as much code as possible in the limited flash memory.
lto = true           # Link Time Optimization: LLVM aanalyzes the whole program at link time, which can lead to better optimizations and smaller code size.
codegen-units = 1    # Build everything in one codegen unit, which allows for better optimization across the whole program, at the cost of longer compile times.
panic = "abort"      # No unwinding, as we have no OS to catch it.
strip = true         # ask compiler to strip symbols from the final binary, which can reduce size. Note that this may make debugging more difficult, as it removes symbol information from the binary.